BASE_URL = "https://cad.onshape.com"

def generate_nonce() -> str: ...

class OnshapeClient:
    def __init__(self, env_file_path: str | None = None, base_url: str | None = None) -> None: ...
    @property
    def base_url(self) -> str: ...
    @base_url.setter
    def base_url(self, base_url: str) -> None: ...
    @property
    def api_call_count(self) -> int: ...
